#!/bin/bash


scp lembot.py haskell@irc.lembrary.com:~/.sopel/modules 
# scp sandbox haskell@irc.lembrary.com:~/.local/bin  
# scp default.cfg haskell@irc.lembrary.com:~/.sopel 
ssh haskell@irc.lembrary.com '~/.local/bin/sopel restart'


