#!/bin/bash


scp lembot.py haskell@irc.lembrary.com:~/.sopel/modules 
# scp sandbox haskell@irc.lembrary.com:~/.local/bin  
# scp default.cfg haskell@irc.lembrary.com:~/.sopel 

# Might have to update PYTHONPATH to get this to work
ssh haskell@irc.lembrary.com "/home/haskell/.local/bin/sopel restart"  


